/// <reference lib="webworker" />
import { cleanupOutdatedCaches, precacheAndRoute } from 'workbox-precaching';

declare let self: ServiceWorkerGlobalScope;

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// Cleanup old caches
cleanupOutdatedCaches();

// --- Push Notification Logic ---

self.addEventListener('push', (event) => {
    if (!event.data) return;

    try {
        const data = event.data.json();
        const title = data.title || '浪跡戰域 (Wanderer\'s Realm)';
        const options: any = {
            body: data.body || '您有新的遊戲通知',
            icon: '/mask-icon.svg', // Ensure this path is correct
            badge: '/favicon.ico',
            data: data.url || '/',
            vibrate: [200, 100, 200],
            tag: data.tag || 'game-notification',
            renotify: true,
            actions: [
                { action: 'open', title: '進入遊戲' }
            ]
        };

        event.waitUntil(
            self.registration.showNotification(title, options)
        );
    } catch (err) {
        console.error('Push event error:', err);
        // Fallback for plain text
        event.waitUntil(
            self.registration.showNotification('浪跡戰域', {
                body: event.data.text()
            })
        );
    }
});

self.addEventListener('notificationclick', (event) => {
    event.notification.close();

    const urlToOpen = event.notification.data || '/';

    event.waitUntil(
        self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clientList) => {
            // If a window is already open, focus it
            for (const client of clientList) {
                if (client.url === urlToOpen && 'focus' in client) {
                    return client.focus();
                }
            }
            // Otherwise, open a new window
            if (self.clients.openWindow) {
                return self.clients.openWindow(urlToOpen);
            }
        })
    );
});
